//
//  CatalogRouter.swift
//  PeixeUrbano
//
//  Created by Matheus Cardoso kuhn on 20/07/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CatalogRoutingLogic {
}

protocol CatalogDataPassing {
    var dataStore: CatalogDataStore? { get }
}

class CatalogRouter: NSObject, CatalogRoutingLogic, CatalogDataPassing {
    
    // MARK: - Variables
    weak var viewController: CatalogViewController?
    var dataStore: CatalogDataStore?
}
