//
//  CatalogInteractor.swift
//  PeixeUrbano
//
//  Created by Matheus Cardoso kuhn on 20/07/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CatalogBusinessLogic {
    func doSomething(request: Catalog.Something.Request)
}

protocol CatalogDataStore {
    //var name: String { get set }
}

class CatalogInteractor: CatalogBusinessLogic, CatalogDataStore {
    
    // MARK: - Variables
    var presenter: CatalogPresentationLogic?
    var worker: CatalogWorker?
    //var name: String = ""
    
    // MARK: - Do something
    func doSomething(request: Catalog.Something.Request) {
        worker = CatalogWorker()
        worker?.doSomeWork()
        
        let response = Catalog.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
