//
//  CatalogWorker.swift
//  PeixeUrbano
//
//  Created by Matheus Cardoso kuhn on 20/07/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CatalogWorker {
    
    /// Request the catalog information.
    ///
    /// - Parameter request: The data to create a request.
    func requestDeals(request: Catalog.CatalogModel.Request) {
        ConnectionUtil.shared.request(on: request.type.requestURL,
                                      method: .get,
                                      parameters: nil,
                                      completion: request.completion)
    }
    
    /// Download a deal's image.
    ///
    /// - Parameter request: The data to create a request.
    func requestImage(request: Catalog.ImageModel.WorkerRequest) {
        ConnectionUtil.shared.downloadImage(on: URL(string: request.url),
                                            completion: request.completion)
    }
    
    /// Download a banner's image.
    ///
    /// - Parameter request: The data to create a request.
    func requestBanner(request: Catalog.Banners.WorkerRequest) {
        ConnectionUtil.shared.downloadImage(on: URL(string: request.url)) { result in
            request.completion(request.index, result)
        }
    }
}
