//
//  CatalogModels.swift
//  PeixeUrbano
//
//  Created by Matheus Cardoso kuhn on 20/07/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Catalog {
    
    enum Loader {
        struct Response {
            let isLoaderVisible: Bool
        }
        struct ViewModel {
            let isLoaderVisible: Bool
        }
    }
    
    enum TypeModel {
        struct Request {
            let type: CatalogType
        }
    }
    
    enum CatalogModel {
        struct Request {
            let type: CatalogType
            let completion: (Result<ServerResponse<CatalogReponse>, Error>) -> Void
        }
        struct Response {
            let catalog: CatalogReponse
        }
        struct ViewModel {
            struct DealModel {
                let isImageCuttedVisible: Bool
                let imageUrl: String
                let partnerName: String
                let title: String
                let priceDescription: String
                let priceSymbol: String
                let price: String
            }
            
            let banners: [Banner]
            let deals: [DealModel]
        }
    }
    
    enum ImageModel {
        struct Request {
            let url: String
            let indexPath: IndexPath
        }
        struct WorkerRequest {
            let url: String
            let completion: (Result<UIImage, Error>) -> Void
        }
        struct Response {
            let image: UIImage
            let indexPath: IndexPath
        }
        struct ViewModel {
            let image: UIImage
            let indexPath: IndexPath
        }
    }
}
