//
//  CatalogPresenter.swift
//  PeixeUrbano
//
//  Created by Matheus Cardoso kuhn on 20/07/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CatalogPresentationLogic {
    func presentSomething(response: Catalog.Something.Response)
}

class CatalogPresenter: CatalogPresentationLogic {
    
    // MARK: - Variables
    weak var viewController: CatalogDisplayLogic?
    
    // MARK: - Do something
    func presentSomething(response: Catalog.Something.Response) {
        let viewModel = Catalog.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
